<?php
require_once "../includes/config.php"; require_once "../includes/auth.php"; requireRole(["hospital"]);
$user_id=(int)$_SESSION["user_id"];$q=mysqli_prepare($conn,"SELECT status FROM users WHERE id=? LIMIT 1");mysqli_stmt_bind_param($q,"i",$user_id);mysqli_stmt_execute($q);$account=mysqli_fetch_assoc(mysqli_stmt_get_result($q))?:[];if(($account["status"]??"pending")!=="active"){http_response_code(403);exit("Your hospital account is awaiting administrator verification.");}
$q=mysqli_prepare($conn,"SELECT id,name,address,city,license_number FROM hospitals WHERE user_id=? LIMIT 1");mysqli_stmt_bind_param($q,"i",$user_id);mysqli_stmt_execute($q);$hospital=mysqli_fetch_assoc(mysqli_stmt_get_result($q))?:[];$hospital_name=trim($hospital["name"]??"");if($hospital_name===""){http_response_code(404);exit("Hospital profile was not found.");}$hid=(int)$hospital["id"];
$q=mysqli_prepare($conn,"SELECT COALESCE(SUM(units),0) units FROM inventory WHERE hospital_id=?");mysqli_stmt_bind_param($q,"i",$hid);mysqli_stmt_execute($q);$inventory=mysqli_fetch_assoc(mysqli_stmt_get_result($q))?:["units"=>0];
$q=mysqli_prepare($conn,"SELECT COUNT(*) requests FROM requests WHERE hospital_id=? AND status IN ('pending','matched')");mysqli_stmt_bind_param($q,"i",$hid);mysqli_stmt_execute($q);$requests=mysqli_fetch_assoc(mysqli_stmt_get_result($q))?:["requests"=>0];
$q=mysqli_prepare($conn,"SELECT COUNT(*) total FROM appointments WHERE hospital_id=? AND appointment_time>=NOW() AND status='scheduled'");mysqli_stmt_bind_param($q,"i",$hid);mysqli_stmt_execute($q);$upcoming_count=mysqli_fetch_assoc(mysqli_stmt_get_result($q))?:["total"=>0];
$q=mysqli_prepare($conn,"SELECT a.appointment_time,u.name donor_name,d.blood_group FROM appointments a INNER JOIN donors d ON d.id=a.donor_id INNER JOIN users u ON u.id=d.user_id WHERE a.hospital_id=? AND a.appointment_time>=NOW() AND a.status='scheduled' ORDER BY a.appointment_time LIMIT 2");mysqli_stmt_bind_param($q,"i",$hid);mysqli_stmt_execute($q);$upcoming=mysqli_stmt_get_result($q);
$q=mysqli_prepare($conn,"SELECT blood_group,units FROM inventory WHERE hospital_id=? ORDER BY units,blood_group LIMIT 4");mysqli_stmt_bind_param($q,"i",$hid);mysqli_stmt_execute($q);$snapshot=mysqli_stmt_get_result($q);
$q=mysqli_prepare($conn,"SELECT GROUP_CONCAT(blood_group ORDER BY blood_group SEPARATOR ', ') groups FROM inventory WHERE hospital_id=? AND units<=5");mysqli_stmt_bind_param($q,"i",$hid);mysqli_stmt_execute($q);$low=mysqli_fetch_assoc(mysqli_stmt_get_result($q))?:["groups"=>""];
$page_title="Dashboard";require "header.php";
?><main class="role-main"><div class="role-container"><p class="role-kicker">Hospital</p><h1 class="role-title"><?= htmlspecialchars($hospital_name) ?></h1><p class="role-subtitle"><?= htmlspecialchars($hospital["address"]??"") ?>, <?= htmlspecialchars($hospital["city"]??"") ?></p><?php if($low["groups"]): ?><div class="hospital-alert"><i class="fa-solid fa-bolt"></i><span><strong>Low stock:</strong> <?= htmlspecialchars($low["groups"]) ?> — consider scheduling more donor appointments.</span></div><?php endif; ?><?php require "tabs.php"; ?><div class="role-grid"><section class="role-panel metric-card"><span class="metric-icon"><i class="fa-solid fa-cube"></i></span><strong class="metric-value"><?= (int)$inventory["units"] ?></strong><span class="metric-label">Total Units in Stock</span></section><section class="role-panel metric-card"><span class="metric-icon"><i class="fa-regular fa-calendar"></i></span><strong class="metric-value"><?= (int)$upcoming_count["total"] ?></strong><span class="metric-label">Upcoming Appointments</span></section><section class="role-panel metric-card"><span class="metric-icon"><i class="fa-solid fa-bolt"></i></span><strong class="metric-value"><?= (int)$requests["requests"] ?></strong><span class="metric-label">Requests Awaiting Fulfillment</span></section></div><div class="dashboard-columns"><section class="dashboard-panel"><h2>Upcoming Appointments</h2><?php if(mysqli_num_rows($upcoming)===0): ?><p>No upcoming appointments.</p><?php endif; ?><?php while($a=mysqli_fetch_assoc($upcoming)): ?><div class="appointment-row"><div><div class="appointment-person"><?= htmlspecialchars($a["donor_name"]) ?> <span>(<?= htmlspecialchars($a["blood_group"]) ?>)</span></div><div class="appointment-date"><?= htmlspecialchars(date("M j, Y g:i A",strtotime($a["appointment_time"]))) ?></div></div><a class="manage-button" href="appointments.php">Manage</a></div><?php endwhile; ?></section><section class="dashboard-panel"><h2>Inventory Snapshot</h2><?php if(mysqli_num_rows($snapshot)===0): ?><p>No inventory recorded.</p><?php endif; ?><?php while($s=mysqli_fetch_assoc($snapshot)): ?><div class="inventory-row"><strong><?= htmlspecialchars($s["blood_group"]) ?></strong><span class="inventory-units <?= (int)$s["units"]<=5?"is-low":"" ?>"><?= (int)$s["units"] ?> units</span></div><?php endwhile; ?></section></div></div></main>
