<?php
require_once "../includes/config.php";
require_once "../includes/auth.php";
requireRole(["donor"]);
$user_id=(int)$_SESSION["user_id"];$message="";
if($_SERVER["REQUEST_METHOD"]==="POST"){$name=trim($_POST["name"]??"");$email=trim($_POST["email"]??"");$phone=trim($_POST["phone"]??"");$blood_group=trim($_POST["blood_group"]??"");$age=(int)($_POST["age"]??0);$weight=(float)($_POST["weight"]??0);$city=trim($_POST["city"]??"");$groups=["A+","A-","B+","B-","AB+","AB-","O+","O-"];
if($name===""||!filter_var($email,FILTER_VALIDATE_EMAIL)||$phone===""||!in_array($blood_group,$groups,true)||$age<18||$weight<=0||$city===""){$message="Please complete every field with valid information.";}else{$user_stmt=mysqli_prepare($conn,"UPDATE users SET name = ?, email = ?, phone = ? WHERE id = ?");mysqli_stmt_bind_param($user_stmt,"sssi",$name,$email,$phone,$user_id);$donor_stmt=mysqli_prepare($conn,"UPDATE donors SET blood_group = ?, age = ?, weight = ?, city = ? WHERE user_id = ?");mysqli_stmt_bind_param($donor_stmt,"sidsi",$blood_group,$age,$weight,$city,$user_id);mysqli_stmt_execute($user_stmt);mysqli_stmt_execute($donor_stmt);$_SESSION["full_name"]=$name;$_SESSION["email"]=$email;$message="Profile saved successfully.";}}
$stmt=mysqli_prepare($conn,"SELECT u.name,u.email,u.phone,d.blood_group,d.age,d.weight,d.city FROM users u INNER JOIN donors d ON d.user_id=u.id WHERE u.id=? LIMIT 1");mysqli_stmt_bind_param($stmt,"i",$user_id);mysqli_stmt_execute($stmt);$profile=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt))?:[];$page_title="Edit Profile";require "header.php";
?><main class="role-main"><div class="role-container"><p class="role-kicker">Donor</p><h1 class="role-title">Edit Profile</h1><?php require "tabs.php"; ?><?php if($message!==""): ?><p class="role-message"><?= htmlspecialchars($message) ?></p><?php endif; ?><form class="role-form" method="post"><div class="role-form-grid"><div><label for="name">Name</label><input id="name" name="name" value="<?= htmlspecialchars($profile["name"]??"") ?>" required></div><div><label for="email">Email</label><input id="email" type="email" name="email" value="<?= htmlspecialchars($profile["email"]??"") ?>" required></div><div class="full"><label for="phone">Phone</label><input id="phone" name="phone" value="<?= htmlspecialchars($profile["phone"]??"") ?>" required></div><div><label for="blood_group">Blood Group</label><select id="blood_group" name="blood_group" required><?php foreach(["A+","A-","B+","B-","AB+","AB-","O+","O-"] as $group): ?><option <?= ($profile["blood_group"]??"")===$group?"selected":"" ?>><?= $group ?></option><?php endforeach; ?></select></div><div><label for="age">Age</label><input id="age" type="number" name="age" min="18" max="100" value="<?= htmlspecialchars($profile["age"]??"") ?>" required></div><div><label for="weight">Weight (kg)</label><input id="weight" type="number" step="0.1" min="1" name="weight" value="<?= htmlspecialchars($profile["weight"]??"") ?>" required></div><div><label for="city">City</label><input id="city" name="city" value="<?= htmlspecialchars($profile["city"]??"") ?>" required></div></div><button class="role-button" type="submit">Save Changes</button></form></div></main>
